name: Build, Create Docker Image, and Push to GitHub Container Registry

on:
  push:
    branches:
      - develop  # Trigger on push to the `main` branch
  pull_request:
    branches:
      - develop  # Trigger on pull requests to the `main` branch
  workflow_dispatch:  # Allow manual workflow runs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version  # Verify Maven installation

      # Step 4: List files in the repository (for debugging)
      - name: List files in the repository
        run: ls -la

      # Step 5: Build ThingsBoard
      - name: Build ThingsBoard
        run: |
          ./mvnw clean install -DskipTests -Dlicense.skip=true || mvn clean install -DskipTests -Dlicense.skip=true
      
      # Step 5.5: Search for Dockerfile
      - name: Search for Dockerfile
        run: find . -name "Dockerfile"
      
      # Step 6: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 7: Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -t ghcr.io/${{ github.repository_owner }}/tb-postgres:latest ./msa/tb/docker-postgres/

      # Step 8: Push Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tb-postgres:latest
