name: Build, Create Docker Image, and Push to GitHub Container Registry

on:
  push:
    branches:
      - develop
      - multi-arch
  pull_request:
    branches:
      - develop
      - multi-arch
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version  # Verify Maven installation

      # Step 4: Build ThingsBoard
      - name: Build ThingsBoard
        run: |
          ./mvnw clean install -DskipTests -Dlicense.skip=true || mvn clean install -DskipTests -Dlicense.skip=true

      # Step 5: Prepare docker build context
      - name: Prepare Docker build context
        run: |
          mkdir -p docker-build
          cp docker-postgres-modified.dockerfile docker-build/Dockerfile
          cp application/target/thingsboard.deb docker-build/
          cp msa/tb/docker-postgres/logback.xml docker-build/
          cp msa/tb/docker-postgres/thingsboard.conf docker-build/
          cp msa/tb/docker-postgres/start-db.sh docker-build/
          cp msa/tb/docker-postgres/stop-db.sh docker-build/
          cp msa/tb/docker-postgres/start-tb.sh docker-build/
          cp msa/tb/docker-postgres/upgrade-tb.sh docker-build/
          cp msa/tb/docker-postgres/install-tb.sh docker-build/
          chmod +x docker-build/*.sh

      # Step 6: Set up Docker Buildx for multi-architecture builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Build and push multi-architecture Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker-build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tb-postgres:latest 